#! /bin/sh
# Bspwm configuration file:

# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Polybar launch
bash $HOME/.config/polybar/launch.sh --cuts &

# wallpaper with feh
feh --bg-fill https://github.com/AlphaLawless/arch-base-install/blob/main/wallpapers/archlinux.jpg?raw=true &

# set keyboard
# setxkbmap -option grp:alt_shit_toggle us & # If you have keyboard american
setxkbmap -option grp:alt_shit_toggle br &

# dunst is a lightweight replacement for the notification-daemons provided by most desktop environments.
dunst &

# picom
picom -b &

# unclutter hide cursor when you do not need it.
unclutter &

# xrandr Multi Monitors
if [[ $(xrandr -q | grep 'HDMI-1 connected') ]]; then
  xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output HDMI-1 --mode 1600x900 --rotate normal --right-of eDP-1 &
else
  bspc monitor -d I II III IV V VI VII VIII
fi

bspc monitor eDP-1 -d I II III IV V
bspc monitor HDMI-1 -d VI VII VIII

bspc config border_width              1.75
bspc config window_gap                12
bspc config bottom_padding            5

bspc config split_ratio               0.52
bspc config borderless_monocle        true
bspc config single_monocle 	          true
bspc config ignore_ewmh_focus	      true

# Mouse config
bspc config pointer_modifier          mod1
bspc config click_to_focus            true
bspc config focus_follows_pointer     true
bspc config pointer_action1           move
bspc config pointer_action2           resize_side
bspc config pointer_action3           resize_corner

xsetroot -cursor_name left_ptr &

# Set the border colors.
bspc config normal_border_color       "#282C34"  # window not active
bspc config active_border_color       "#282c34" # ?
bspc config focused_border_color      "#77DF80" # window active
bspc config presel_feedback_color     "#282C34" # ?

# Custom rules
bspc rule -a kitty desktop='^2' state=tiled follow=on
bspc rule -a Virt-manager desktop='^5' state=floating follow=on
bspc rule -a firefox desktop='^3' state=tiled follow=on
bspc rule -a Gimp desktop='^5' state=tiled follow=on focus=on
bspc rule -a Inkscape desktop='^5' state=tiled follow=on
bspc rule -a Org.gnome.Nautilus desktop='^1' state=floating

